code --list-extensions | % { "code --install-extension $_" }

code --install-extension adpyke.codesnap
code --install-extension alexcvzz.vscode-sqlite
code --install-extension alfnielsen.vsc-organize-imports
code --install-extension angular.ng-template
code --install-extension bierner.lit-html
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension cyrilletuzi.angular-schematics
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ebrithil30.vscode-ts-auto-return-type
code --install-extension editorconfig.editorconfig
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension funkyremi.vscode-google-translate
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension hediet.vscode-drawio
code --install-extension humao.rest-client
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension matt-meyers.vscode-dbml
code --install-extension mhutchie.git-graph
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension mitchdenny.ecdc
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-playwright.playwright
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.powershell
code --install-extension naumovs.color-highlight
code --install-extension pkief.material-icon-theme
code --install-extension raidou.calc
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
code --install-extension styled-components.vscode-styled-components
code --install-extension tao-cumplido.inspector-hex
code --install-extension tyriar.sort-lines
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension vivaxy.vscode-conventional-commits
code --install-extension wallabyjs.console-ninja
